# Generated by Django 5.2.6 on 2026-09-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('onefd', 'تسجيلات بالمراسلة'), ('print', 'طبع وثائق'), ('extract', 'استخراج وثائق'), ('write', 'خدمات كتابية'), ('gold_card', 'بطاقة ذهبية'), ('travel', 'طلب سفر'), ('justice', 'وزارة العدل'), ('ansej', 'أنساج / أنام')], max_length=30)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
